### PR TITLE
Updated android auto certificate and private key files

### PR DESCRIPTION
**Pull request by smirn0v**

### CODE REVIEW

**Comment by dylangerdaly** [comment]
What's this for exactly?

**Comment by tomasz-grobelny** [comment]
These are newer key and certificate used to authenticate to headunit. Unfortunately did not ave time to verify on my headunit yet.

**Comment by gamelaster** [comment]
How to dump those keys? I dumped keys from Headunit, but I have issues to get AA (Phone) keys. Thanks

**Comment by tomasz-grobelny** [comment]
Please have a look here for discussion: https://github.com/tomasz-grobelny/AACS/issues/15. But I am wondering how you dumped the keys from headunit - that would be interesting to know.

**Pull request merged**
